projects:
  ecodrive:
    schemaPath: amplify/backend/api/ecodrive/build/schema.graphql
    includes:
      - src/modules/api/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/modules/api/API.ts
        docsFilePath: src/modules/api/graphql
        region: eu-west-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
